### PR TITLE
take control of linting and add material ui

### PR DESCRIPTION
**Pull request by pascalwhoop**
This PR does two things:
- allows us to take control of linting in frontend by setting webpack to use the rc file (it was ignoring it)
- adds material UI to frontend

### CODE REVIEW

**Comment by pascalwhoop** [comment]
Warnings are now shown as errors in CI. This is a fair setup I guess. I'll add `CI=true` to the `yarn lint` command so one can manually run "CI style lint" explicitly

**Comment by gpavone** [comment]
I've just noticed that the CI pipeline failed. It looks like we still have some linting errors.

**Comment by pascalwhoop** [comment]
all green now but merge conflicts. Will resolve through rebase

**Comment by pascalwhoop** [comment]
I integrated the button into the top bar but I don't like how it looks

Do you want to see if we can work with a material-ui pop up of some sort for the login flow?

**Pull request merged**
